version: "3.9"
services:
  app:
    image: dotnet-docker
    volumes:
      - ./code:/app
    working_dir: /app
    command: dotnet run
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Development